AC-33 Project architecture and main functionality
Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console-Services pull request #1
Opened 2024-10-22 22:11 UTC by ricardogamboagap

2024-10-22 22:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console-Services?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console-Services?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Alliance-OSS/Ed-Fi-Admin-Console-Services?pullRequest=1) it.</sub>

2024-10-22 23:05 UTC, jagudelo-gap requested changes

2024-10-22 23:05 UTC, jagudelo-gap commented on Admin-Console-Health-Check-Service/Admin-Console-Health-Check-Service/Response/GetTokenResponse.cs
> +﻿using System.Text.Json.Serialization;
We use the namespaces without brackets, eg

```
// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

//Namespace has no valid name, has to be replaced with EdFi.AdminConsoleHealthCheck.Configuration
﻿namespace Admin_Console_Health_Check_Service.Response;
public class GetTokenResponse
    {
        [JsonPropertyName("access_token")]
        public string AccessToken { get; set; }

        [JsonPropertyName("token_type")]
        public string TokenType { get; set; }

        [JsonPropertyName("expires_in")]
        public int ExpiresIn { get; set; }
    }
```
Also, we have to include the license header

// SPDX-License-Identifier: Apache-2.0
```
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
```

2024-10-23 16:47 UTC, dfernandez-gap commented on Admin-Console-Health-Check-Service/Admin-Console-Health-Check-Service/Admin-Console-Health-Check-Service.http
¿Should we keep this .http file? @jagudelo-gap

2024-10-23 21:47 UTC, jagudelo-gap commented on Admin-Console-Health-Check-Service/Admin-Console-Health-Check-Service/Admin-Console-Health-Check-Service.http
@dfernandez-gap 
We will keep it for the time being. We will decide later if we want to use it for the e2e tests.

2024-10-28 16:07 UTC, jagudelo-gap approved these changes

2024-10-28 16:08 UTC, merged